### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by hahaSAW** [96486d9b/lol-heroes#1]
@96486d9b 很酷！不过有没有能把终极皮肤的其他模型都展示出来的 比如大元素使
好像这个网站可以http://lol.pifupai.com/3dmodels?champion=99&skin=7#selectSkin

**Comment by antct** [comment]
谢谢支持，已经添加了对应的大元素使，但是其他终极皮肤的模型似乎没有呢~

**Comment by hahaSAW** [comment]
好快！
没有其他的应该是资源问题吧
https://teemo.gg/model-viewer 这个应该是比较全的

**Comment by antct** [comment]
嗯嗯是的，模型挺难弄的，我之前尝试过从这个网站导入模型，但它封装的太厉害了，直接是wasm格式的。
